import {
    SiReact,
    SiNextdotjs,
    SiTypescript,
    SiJavascript,
    SiTailwindcss,
    SiNodedotjs,
    SiExpress,
    SiPython,
    SiFastapi,
    SiJsonwebtokens,
    SiMongodb,
    SiPostgresql,
    SiSupabase,
    SiFirebase,
    SiExpo,
    SiOpenai,
    SiHuggingface,
    SiLangchain,
    SiGooglegemini,
    SiDocker,
    SiAmazon,
    SiGit,
    SiPostman,
    SiLinux,
    SiNumpy,
    SiPandas,
    SiStreamlit,
    SiSocketdotio,
    SiGraphql,
    SiPytorch,
    SiScikitlearn,
    SiGo,
    SiNestjs,
    SiSolana,
    SiRust,
    SiDrizzle,
    SiPrisma,
    SiRedis,
    SiElasticsearch,
    SiTrpc,
    SiGithub,
    SiGithubactions,
    SiClerk,
    SiGooglemaps,
    SiKubernetes,
} from "react-icons/si";
import { FaServer, FaRobot, FaAnchor, FaMobileAlt, FaDatabase, FaCode, FaShieldAlt, FaTerminal } from "react-icons/fa";

export const techIcons: Record<string, any> = {
    // Languages
    "TypeScript": SiTypescript,
    "JavaScript": SiJavascript,
    "Python": SiPython,
    "Go": SiGo,
    "Rust": SiRust,
    "SQL": FaDatabase,
    "C++": FaCode,

    // Frontend
    "React": SiReact,
    "React.js": SiReact,
    "Next.js": SiNextdotjs,
    "Nextjs": SiNextdotjs,
    "Tailwind CSS": SiTailwindcss,
    "Tailwind": SiTailwindcss,
    "React Native": FaMobileAlt,
    "Expo": SiExpo,
    "Redux": SiReact,
    "Zustand": SiReact,
    "Framer Motion": SiReact,

    // Backend
    "Node.js": SiNodedotjs,
    "Express.js": SiExpress,
    "Express": SiExpress,
    "FastAPI": SiFastapi,
    "NestJS": SiNestjs,
    "Nestjs": SiNestjs,
    "Gin": SiGo,
    "Socket.io": SiSocketdotio,
    "Socket": SiSocketdotio,
    "gRPC": FaServer,
    "GraphQL": SiGraphql,
    "REST APIs": FaServer,
    "JWT": SiJsonwebtokens,


    // Databases
    "PostgreSQL": SiPostgresql,
    "PSQL": SiPostgresql,
    "MongoDB": SiMongodb,
    "Supabase": SiSupabase,
    "Firebase": SiFirebase,
    "Drizzle ORM": SiDrizzle,
    "Drizzle": SiDrizzle,
    "Prisma": SiPrisma,
    "Turso": SiSupabase,
    "SQLite": FaDatabase,
    "Redis": SiRedis,
    "Elasticsearch": SiElasticsearch,

    // AI/ML
    "OpenAI": SiOpenai,
    "Hugging Face": SiHuggingface,
    "HuggingFace": SiHuggingface,
    "LangChain": SiLangchain,
    "Langchain": SiLangchain,
    "LangGraph": SiLangchain,
    "NumPy": SiNumpy,
    "Pandas": SiPandas,
    "Scikit-learn": SiScikitlearn,
    "Transformers": FaRobot,
    "Groq": FaRobot,
    "Gemini": SiGooglegemini,
    "Gemini API": SiGooglegemini,
    "PyTorch": SiPytorch,
    "Streamlit": SiStreamlit,
    "AI Agents": FaRobot,
    "RAG": FaDatabase,
    "Vector DB": FaDatabase,
    "Vector Databases": FaDatabase,



    // Blockchain / Web3
    "Solana": SiSolana,
    "Anchor": FaAnchor,
    "Web3.js": SiJavascript,
    "Solana Wallet Adapter": SiSolana,

    // DevOps & Cloud
    "Docker": SiDocker,
    "kubernetes": SiKubernetes,
    "Kubernetes": SiKubernetes,
    "AWS": SiAmazon,
    "Vercel": SiNextdotjs,
    "Linux": SiLinux,
    "Git": SiGit,
    "Postman": SiPostman,
    "GitHub API": SiGithub,
    "GitHub Actions": SiGithubactions,
    "CI/CD": SiGithubactions,

    // Auth & APIs
    "JWT Authentication": SiJsonwebtokens,
    "JWT Auth": SiJsonwebtokens,
    "Clerk": SiClerk,
    "Google Maps API": SiGooglemaps,

    // AI extras
    "OpenAI GPT": SiOpenai,
    "Vercel AI SDK": SiNextdotjs,
    "CrewAI": FaRobot,
    "ElevenLabs": FaRobot,
    "Whisper": FaRobot,
    "Gradio": SiPython,
    "spaCy": SiPython,
    "Scrapy": SiPython,
    "BeautifulSoup": SiPython,
    "LLaMA": FaRobot,
    "Meta Llama": FaRobot,
    "Few-Shot Learning": FaRobot,
    "Decodo API": FaDatabase,
    "Jina Embeddings": FaDatabase,
    "Qdrant": FaDatabase,
    "AstraDB": FaDatabase,
    "NetworkX": FaCode,
    "PyViz": FaCode,

    // Security
    "Security": FaShieldAlt,

    // CLI / System
    "TUI": FaTerminal,
    "Terminal UI": FaTerminal,
    "CLI": FaTerminal,
    "Cobra": SiGo,
    "Viper": SiGo,
    "Clap": SiRust,
    "Tokio": SiRust,
    "Reqwest": SiRust,
    "Serde": SiRust,

    // Other
    "LLM APIs": FaRobot,
    "SSE": FaServer,
    "WebSockets": SiSocketdotio,
    "Microservices": FaServer,
    "React Query": SiReact,
    "Async Storage": FaMobileAlt,
    "Expo Notifications": SiExpo,
    "YAML (workflows)": FaCode,
    "Next.js 16": SiNextdotjs,
    "OpenAI / Gemini": SiOpenai,
};
